name: TEST
dependencies:
  - python=3.7
  - pytest
  - six
  - numpy
  - scipy
  - lxml
  - matplotlib-base >=3.0.2
  - dask
  - netcdf4
  - hdf5
  - hdf4
  - nco >=4.8.1
  - pyproj
  - pillow
  - cmocean
  - progressbar2
  - requests
  - shapely
  - cartopy >=0.18.0
  - geometric_features
  - gsw
  - pyremap
  - mpas_tools
  - sphinx
  - mock
  - sphinx_rtd_theme
  - numpydoc
  - tabulate >=0.8.2
  - m2r
  - pip:
    # following https://github.com/xgcm/xgcm/blob/master/ci/environment-py37-upstream-master.yml
    - git+https://github.com/pydata/xarray.git
