channels:
  - conda-forge
dependencies:
  - pytest
  - six
  - numpy<1.16.0
  - scipy
  - lxml
  - xarray>=0.10.0
  - matplotlib
  - dask
  - netcdf4
  - hdf5
  - hdf4
  - nco>=4.7.9
  - pyproj
  - pillow
  - cmocean
  - progressbar2
  - requests
  - shapely
  - proj4 < 6.0.0
