name: mpas-analysis-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - xarray
  - dask
  - bottleneck
  - basemap
  - lxml
  - hdf5
  - hdf4
  - nco
  - pyproj
  - pillow
  - cmocean
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - tabulate >= 0.8.2
  - m2r
  - shapely
